promotion/urls.py
from django.urls import path, reverse_lazy

from promotion import views


app_name = 'promotion'


urlpatterns = [
    path('', views.PromotionView.as_view(),
         name="show_promotion"),
    path('select_wallet', views.SelectWalletView.as_view(),
         name="select_wallet"),
    path('contract', views.ContractView.as_view(),
         name="contract"),
    path('contract/1', views.ThanksView.as_view(),
         name="thanks"),
]

promotion/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from oidc4vp.models import Authorization


class Promotion(models.Model):
    class Types(models.IntegerChoices):
        VULNERABLE = 1, _("Financial vulnerability")

    name = models.CharField(max_length=250)
    discount = models.PositiveSmallIntegerField(
        choices=Types.choices,
    )
    authorize = models.ForeignKey(
        Authorization,
        on_delete=models.CASCADE,
        related_name='promotions',
        null=True,
    )

    def get_url(self, code):
        url = "{}?code={}".format(
            reverse_lazy("promotion:contract"),
            code
        )
        return url

    def get_discount(self, price):
        return price - price*0.25

promotion/forms.py
from django import forms
from django.conf import settings

from oidc4vp.models import Organization, Authorization
from promotion.models import Promotion


class WalletForm(forms.Form):
    organization = forms.ChoiceField(
        choices=[],
        widget=forms.Select(attrs={'class': 'form-select'})
    )

    def __init__(self, *args, **kwargs):
        self.presentation_definition = kwargs.pop('presentation_definition', [])
        super().__init__(*args, **kwargs)
        self.fields['organization'].choices = [
            (x.id, x.name) for x in Organization.objects.exclude(
                domain=settings.DOMAIN
            )
        ]

    def save(self, commit=True):
        self.org = Organization.objects.filter(
            id=self.data['organization']
        )
        if not self.org.exists():
            return

        self.org = self.org[0]

        self.authorization = Authorization(
            organization=self.org,
            presentation_definition=self.presentation_definition,
        )
        self.promotion = Promotion(
            discount = Promotion.Types.VULNERABLE.value,
            authorize = self.authorization
        )

        if commit:
            self.authorization.save()
            self.promotion.save()

            return self.authorization.authorize()

        return


class ContractForm(forms.Form):
    nif = forms.CharField()
    name = forms.CharField()
    first_last_name = forms.CharField()
    second_last_name = forms.CharField()
    email = forms.CharField()
    email_repeat = forms.CharField()
    telephone = forms.CharField()
    birthday = forms.CharField()
    gen = forms.CharField()
    lang = forms.CharField()

promotion/views.py
import json

from django.conf import settings
from django.views.generic.edit import View, FormView
from django.shortcuts import redirect
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.http import HttpResponse

from oidc4vp.models import Authorization
from promotion.forms import WalletForm, ContractForm


class PromotionView(View):
    template_name = "somconnexio_tarifes_mobil.html"
    def get(self, request, *args, **kwargs):
        self.context = {}
        template = get_template(
            self.template_name,
        ).render()
        return HttpResponse(template)

class ThanksView(View):
    template_name = "somconnexio_thanks.html"
    def get(self, request, *args, **kwargs):
        self.context = {}
        template = get_template(
            self.template_name,
        ).render()
        return HttpResponse(template)


class ContractView(FormView):
    template_name = "somconnexio_contract.html"
    promotion = None
    vp_token = None
    authorization = None
    form_class = ContractForm
    success_url = reverse_lazy('promotion:thanks')

    def get_context_data(self, **kwargs):
        self.context = super().get_context_data(**kwargs)
        code = self.request.GET.get("code")
        self.get_discount(code)
        self.context.update({
            "promotion": self.promotion,
            "verificable_presentation": self.vp_token,
            "sim": 10.0,
            "mensual": 15.0,
            "total": 25.0
        })
        if self.promotion:
            self.context['sim'] = self.promotion.get_discount(self.context["sim"])
            self.context['mensual'] = self.promotion.get_discount(self.context["mensual"])
            self.context['total'] = self.promotion.get_discount(self.context["total"])

        if self.vp_token:
            self.context['verificable_presentation'] = self.vp_token

        return self.context
        
        
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        code = self.request.GET.get("code")
        self.get_discount(code)
        if not self.vp_token:
            return kwargs

        self.vp_token.get_user_info()
        kwargs['initial']["nif"] = self.vp_token.user_info.get("identityNumber", '')
        kwargs['initial']["name"] = self.vp_token.user_info.get("firstName", '')
        kwargs['initial']["first_last_name"] = self.vp_token.user_info.get("lastName", '')
        kwargs['initial']["second_last_name"] = self.vp_token.user_info.get("second_last_name", '')
        kwargs['initial']["email"] = self.vp_token.user_info.get("email", '')
        kwargs['initial']["email_repeat"] = self.vp_token.user_info.get("email", '')
        kwargs['initial']["telephone"] = self.vp_token.user_info.get("telephone", '')
        kwargs['initial']["birthday"] = self.vp_token.user_info.get("birthday", '')
        kwargs['initial']["gen"] = self.vp_token.user_info.get("gen", '')
        kwargs['initial']["lang"] = self.vp_token.user_info.get("lang", '')
        return kwargs

    def form_valid(self, form):
        return super().form_valid(form)

    def get_discount(self, code):
        if not code:
            return
        if self.authorization:
            return

        self.authorization = Authorization.objects.filter(
            code=code,
            code_used=False
        ).first()
        if self.authorization:
            if self.authorization.promotions.exists():
                self.promotion = self.authorization.promotions.all()[0]
            if self.authorization.vp_tokens.exists():
                self.vp_token = self.authorization.vp_tokens.all()[0]
        

class SelectWalletView(FormView):
    template_name = "select_wallet.html"
    form_class = WalletForm
    success_url = reverse_lazy('promotion:select_wallet')

    def get_form_kwargs(self):
        presentation = self.get_response_uri()
        if not presentation:
            presentation = json.dumps(
            settings.SUPPORTED_CREDENTIALS
        )
        kwargs = super().get_form_kwargs()
        kwargs['presentation_definition'] = presentation
        return kwargs

    def form_valid(self, form):
        url = form.save()
        return redirect(url)

    def get_response_uri(self):
        path = self.request.get_full_path().split("?")
        if len(path) < 2:
            return

        args = dict(
            [x.split("=") for x in path[1].split("&")]
        )
        response_uri = args.get('response_uri')

        self.request.session["response_uri"] = response_uri
        presentation = args.get('presentation_definition')

        for x in settings.SUPPORTED_CREDENTIALS:
            if x in presentation:
                return json.dumps([x])

promotion/templates/select_wallet.html
{% load i18n static %}

<!doctype html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="NONE,NOARCHIVE" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Pangea">
    <title>{% block title %}{% if title %}{{ title }} – {% endif %}Pangea{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href= "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link href="{% static "/css/bootstrap.min.css" %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

  
    <!-- Custom styles for this template -->
    <link href="{% static "/css/dashboard.css" %}" rel="stylesheet">
  </head>
<body id="body-login">
    <header class="navbar navbar-dark sticky-top bg-grey flex-md-nowrap p-0 shadow" style="background-color: #712547;">
      <div class="navbar-nav navbar-sub-brand">
      </div>
      <div class="navbar-nav">
      </div>
    </header>

    <div class="container-fluid">
      <div class="row">
        <main class="col-md-12 bt-5">
          {% for message in messages %}
          <div class="alert alert-{{ message.tags|default:'info' }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}

          <div class="jumbotron vertical-center">
              <div id="login-wrapper" class="container" style="width: 430px;">
                  <div id="login-content" class="rounded">
                      <div id="login-branding">
                      </div><!-- /login-branding -->
                      <div class="mt-5">
                        {% load i18n %}
                        {% load django_bootstrap5 %}
                        <form role="form" method="post">
                        {% csrf_token %}
                        <div class="row">
                          <div class="col">
                            {% bootstrap_form form %}
                          </div>
                        </div>
                        <div class="form-actions-no-box">
                          <input class="btn btn-green-admin" type="submit" name="submit" value="{% trans 'Go' %}" />
                        </div>

                        </form>
                      </div><!-- /.row-fluid -->
                  </div>
                  <!--/#login-content-->
              </div><!-- /#login-wrapper -->
          </div><!-- /.jumbotron -->

        </main>
      </div>
    </div>

    <script src="/static/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
    <script src="/static/js/dashboard.js"></script>
  </body>
</html>

promotion/templates/select_wallet_setem.html
{% load i18n static %}

<!doctype html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="NONE,NOARCHIVE" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Setem">
    <title>{% block title %}{% if title %}{{ title }} – {% endif %}Setem{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href= "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link href="{% static "/css/bootstrap.min.css" %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

  
    <!-- Custom styles for this template -->
    <link href="{% static "/css/dashboard.css" %}" rel="stylesheet">
  </head>
<body id="body-login">
    <header class="navbar navbar-dark sticky-top bg-grey flex-md-nowrap p-0 shadow" style="background-color: #c4a812;">
      <div class="navbar-nav navbar-sub-brand">
      </div>
      <div class="navbar-nav">
      </div>
    </header>

    <div class="container-fluid">
      <div class="row">
        <main class="col-md-12 bt-5">
          {% for message in messages %}
          <div class="alert alert-{{ message.tags|default:'info' }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}

          <div class="jumbotron vertical-center">
              <div id="login-wrapper" class="container" style="width: 430px;">
                  <div id="login-content" class="rounded">
                      <div id="login-branding">
                      </div><!-- /login-branding -->
                      <div class="mt-5">
                        {% load i18n %}
                        {% load django_bootstrap5 %}
                        <form role="form" method="post">
                        {% csrf_token %}
                        <div class="row">
                          <div class="col">
                            {% bootstrap_form form %}
                          </div>
                        </div>
                        <div class="form-actions-no-box">
                          <input class="btn btn-green-admin" type="submit" name="submit" value="{% trans 'Go' %}" />
                        </div>

                        </form>
                      </div><!-- /.row-fluid -->
                  </div>
                  <!--/#login-content-->
              </div><!-- /#login-wrapper -->
          </div><!-- /.jumbotron -->

        </main>
      </div>
    </div>

    <script src="/static/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
    <script src="/static/js/dashboard.js"></script>
  </body>
</html>

promotion/templates/somconnexio_contract.html
{% load i18n static %}

<!doctype html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="NONE,NOARCHIVE" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Pangea">
    <title>{% block title %}{% if title %}{{ title }} – {% endif %}Pangea{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href= "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link href="{% static "/css/bootstrap.min.css" %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

  
    <!-- Custom styles for this template -->
    <link href="{% static "/css/dashboard.css" %}" rel="stylesheet">
  </head>
<body id="body-login">
    <header class="navbar navbar-dark sticky-top bg-grey flex-md-nowrap p-0 shadow" style="background-color: #712547;">
      <div class="navbar-nav navbar-sub-brand">
      </div>
      <div class="navbar-nav">
      </div>
    </header>

    <div class="container">
      <div class="row mt-5">
        <div class="col">
					{% load i18n %}
					{% load django_bootstrap5 %}
					<form role="form" method="post">
						{% csrf_token %}
						{% if form.errors %}
						<div class="alert alert-danger alert-icon alert-icon-border alert-dismissible" role="alert">
						  <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
						  <div class="message">
						    <button class="close" type="button" data-dismiss="alert" aria-label="Close">
						    <span class="mdi mdi-close" aria-hidden="true"></span>
						    </button>
						    {% for field, error in form.errors.items %}
						      {{ error }}
						    {% endfor %}
						  </div>
						</div>
						{% endif %}
						{% bootstrap_form form %}
						<div class="form-actions-no-box">
						  <a class="btn btn-grey" href="{% url 'promotion:show_promotion' %}">{% trans "Cancel" %}</a>
						  <input class="btn btn-green-admin" type="submit" name="submit" value="{% trans 'Continue' %}" />
						</div>
					</form>
        </div>
        <div class="col-3">
					<ul id="dynfaq">
						<strong>Resum</strong>
						<li style="padding-left: 15px;">
							Imports inicials
						</li>
						<li style="padding-left: 15px;">
							Tarjeta SIM {{ sim }}€
						</li>
						<li style="padding-left: 15px;">
							Factura mensual
						</li>
						<li style="padding-left: 15px;">
							{{ mensual }}€
						</li>
						Total {{ total }}€ (IVA inclòs)
					</ul>
        </div>
      </div>
    </div>

    <script src="/static/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
    <script src="/static/js/dashboard.js"></script>
  </body>
</html>

promotion/templates/somconnexio_tarifes_mobil.html
{% load i18n static %}

<!doctype html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="NONE,NOARCHIVE" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Pangea">
    <title>{% block title %}{% if title %}{{ title }} – {% endif %}Pangea{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href= "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link href="{% static "/css/bootstrap.min.css" %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

  
    <!-- Custom styles for this template -->
    <link href="{% static "/css/dashboard.css" %}" rel="stylesheet">
  </head>
<body id="body-login">
    <header class="navbar navbar-dark sticky-top bg-grey flex-md-nowrap p-0 shadow" style="background-color: #712547;">
      <div class="navbar-nav navbar-sub-brand">
      </div>
      <div class="navbar-nav">
      </div>
    </header>

    <div class="container">
      <div class="row">
        <div class="col bt-5">
        	<div><h1>Fibra por solo 7€ al mes.</h1></div>
        </div>
      </div>
      <div class="row mt-5">
        <div class="col bt-5">
        	<div><h4><a href="{% url 'promotion:contract' %}">Contractar normal</a></h4></div>
        </div>
        <div class="col bt-5">
        	<div><h4><a href="{% url 'promotion:select_wallet' %}">Contractar amb credencial</a></h4></div>
        </div>
      </div>
    </div>

    <script src="/static/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
    <script src="/static/js/dashboard.js"></script>
  </body>
</html>