idhub/urls.py
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.urls import path, reverse_lazy
from .views import (
    AvailableDidView,
    LoginView,
    PasswordResetView,
    PasswordResetConfirmView,
    ServeDidView,
    ServeDidRegistryView,
    SchemaView,
    ContextView,
    ContextFileView,
    DobleFactorSendView,
)
from .admin import views as views_admin
from .user import views as views_user
# from .verification_portal import views as views_verification_portal

app_name = 'idhub'

urlpatterns = [
    path("", RedirectView.as_view(url=reverse_lazy('idhub:login'),
        permanent=False)),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('auth/password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('auth/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='auth/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path('auth/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path('auth/reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='auth/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),

    # User
    path('user/dashboard/', views_user.DashboardView.as_view(),
        name='user_dashboard'),
    path('user/profile/', views_user.ProfileView.as_view(),
        name='user_profile'),
    path('user/roles/', views_user.RolesView.as_view(),
        name='user_roles'),
    path('user/gdpr/', views_user.GDPRView.as_view(),
        name='user_gdpr'),
    path('user/identities/', views_user.DidsView.as_view(),
        name='user_dids'),
    path('user/dids/new/', views_user.DidRegisterView.as_view(),
        name='user_dids_new'),
    path('user/dids/<int:pk>/', views_user.DidEditView.as_view(),
        name='user_dids_edit'),
    path('user/dids/<int:pk>/del/', views_user.DidDeleteView.as_view(),
        name='user_dids_del'),
    path('user/credentials/', views_user.CredentialsView.as_view(),
        name='user_credentials'),
    path('user/credentials/<int:pk>', views_user.CredentialView.as_view(),
        name='user_credential'),
    path('user/credentials/<int:pk>/html/', views_user.CredentialHTMLView.as_view(),
        name='user_credential_html'),
    path('user/credentials/<int:pk>/pdf/', views_user.CredentialPdfView.as_view(),
        name='user_credential_pdf'),
    path('user/credentials/<int:pk>/call_oracle', views_user.CallOracleView.as_view(),
        name='call_oracle'),
    path('credentials/<int:pk>/', views_user.CredentialJsonView.as_view(),
        name='user_credential_json'),
    path('public/credentials/<str:pk>/', views_user.PublicCredentialJsonView.as_view(),
        name='public_credential_json'),
    path('user/credentials/request/',
        views_user.CredentialsRequestView.as_view(),
        name='user_credentials_request'),
    path('user/credentials_presentation/demand',
        views_user.DemandAuthorizationView.as_view(),
        name='user_demand_authorization'),
    path('user/terms/', views_user.TermsAndConditionsView.as_view(),
        name='user_terms_and_conditions'),

    path('waiting/', views_user.WaitingView.as_view(),
        name='user_waiting'),

    # Admin
    path('admin/dashboard/', views_admin.DashboardView.as_view(),
        name='admin_dashboard'),
    path('admin/people/', views_admin.PeopleListView.as_view(),
        name='admin_people_list'),
    path('admin/people/<int:pk>', views_admin.PeopleView.as_view(),
        name='admin_people'),
    path('admin/people/<int:pk>/edit', views_admin.PeopleEditView.as_view(),
        name='admin_people_edit'),
    path('admin/people/<int:pk>/del', views_admin.PeopleDeleteView.as_view(),
        name='admin_people_delete'),
    path('admin/people/<int:pk>/activate', views_admin.PeopleActivateView.as_view(),
        name='admin_people_activate'),
    path('admin/people/new/', views_admin.PeopleRegisterView.as_view(),
        name='admin_people_new'),
    path('admin/people/<int:pk>/membership/new/', views_admin.PeopleMembershipRegisterView.as_view(),
        name='admin_people_membership_new'),
    path('admin/membership/<int:pk>/edit/', views_admin.PeopleMembershipEditView.as_view(),
        name='admin_people_membership_edit'),
    path('admin/membership/<int:pk>/del/', views_admin.PeopleMembershipDeleteView.as_view(),
        name='admin_people_membership_del'),
    path('admin/people/<int:pk>/rol/new/', views_admin.PeopleRolRegisterView.as_view(),
        name='admin_people_rol_new'),
    path('admin/people/<int:pk>/rol/edit/', views_admin.PeopleRolEditView.as_view(),
        name='admin_people_rol_edit'),
    path('admin/people/<int:pk>/rol/del/', views_admin.PeopleRolDeleteView.as_view(),
        name='admin_people_rol_del'),
    path('admin/roles/', views_admin.RolesView.as_view(),
        name='admin_roles'),
    path('admin/roles/new', views_admin.RolRegisterView.as_view(),
        name='admin_rol_new'),
    path('admin/roles/<int:pk>', views_admin.RolEditView.as_view(),
        name='admin_rol_edit'),
    path('admin/roles/<int:pk>/del', views_admin.RolDeleteView.as_view(),
        name='admin_rol_del'),
    path('admin/services/', views_admin.ServicesView.as_view(),
        name='admin_services'),
    path('admin/services/new', views_admin.ServiceRegisterView.as_view(),
        name='admin_service_new'),
    path('admin/services/<int:pk>', views_admin.ServiceEditView.as_view(),
        name='admin_service_edit'),
    path('admin/services/<int:pk>/del', views_admin.ServiceDeleteView.as_view(),
        name='admin_service_del'),
    path('admin/credentials/', views_admin.CredentialsView.as_view(),
        name='admin_credentials'),
    path('admin/credentials/<int:pk>/', views_admin.CredentialView.as_view(),
        name='admin_credential'),
    path('admin/credentials/<int:pk>/json', views_admin.CredentialJsonView.as_view(),
        name='admin_credential_json'),
    path('admin/credentials/<int:pk>/revoke/', views_admin.RevokeCredentialsView.as_view(),
        name='admin_credentials_revoke'),
    path('admin/credentials/<int:pk>/del/', views_admin.DeleteCredentialsView.as_view(),
        name='admin_credentials_delete'),
    path('admin/wallet/identities/', views_admin.DidsView.as_view(),
        name='admin_dids'),
    path('admin/dids/new/', views_admin.DidRegisterView.as_view(),
        name='admin_dids_new'),
    path('admin/dids/<int:pk>/', views_admin.DidEditView.as_view(),
        name='admin_dids_edit'),
    path('admin/dids/<int:pk>/del/', views_admin.DidDeleteView.as_view(),
        name='admin_dids_del'),
    path('admin/wallet/credentials/', views_admin.WalletCredentialsView.as_view(),
        name='admin_wallet_credentials'),
    path('admin/wallet/config/eidas1/', views_admin.WalletConfigEidas1sView.as_view(),
        name='admin_wallet_config_eidas1'),
    path('admin/schemas/', views_admin.SchemasView.as_view(),
        name='admin_schemas'),
    path('admin/schemas/<int:pk>/del/', views_admin.SchemasDeleteView.as_view(),
        name='admin_schemas_del'),
    path('admin/schemas/<int:pk>/', views_admin.SchemasDownloadView.as_view(),
        name='admin_schemas_download'),
    path('admin/schemas/new', views_admin.SchemasNewView.as_view(),
        name='admin_schemas_new'),
    path('admin/schemas/enable', views_admin.SchemasEnableView.as_view(),
        name='admin_schemas_enable'),
    path('admin/schemas/upload', views_admin.SchemasUploadView.as_view(),
        name='admin_schemas_upload'),
    path('admin/schemas/<int:pk>/template/excel', views_admin.TemplateExcelDownloadView.as_view(),
        name='admin_schemas_template_excel'),
    path('admin/schemas/enable/<str:file_schema>', views_admin.SchemasEnableAddView.as_view(),
        name='admin_schemas_enable_add'),
    path('admin/import', views_admin.ImportView.as_view(),
        name='admin_import'),
    path('admin/terms/', views_admin.TermsAndConditionsView.as_view(),
        name='admin_terms_and_conditions'),
    path('admin/import/new', views_admin.ImportAddView.as_view(),
        name='admin_import_add'),
    path('admin/import/<int:pk>/del', views_admin.ImportDeleteView.as_view(),
        name='admin_import_del'),
    path('admin/enc/',  views_admin.EncryptionKeyView.as_view(), name='encryption_key'),
    path('admin/auth/<uuid:admin2fauth>', views_admin.DobleFactorAuthView.as_view(),
        name='admin_2fauth'),
    path('admin/auth/2f/', DobleFactorSendView.as_view(), name='confirm_send_2f'),
    path('admin/templates_pdf', views_admin.VCTemplatesPdfView.as_view(), name='admin_templates_pdf'),
    path('admin/templates_pdf/new/',
         views_admin.VCTemplatePdfNewView.as_view(), name='admin_new_template_pdf'),
    path('admin/templates_pdf/<int:pk>/del/',
         views_admin.VCTemplatePdfDeleteView.as_view(), name='admin_template_pdf_del'),
    path('admin/templates_pdf/<int:pk>/render/',
         views_admin.VCTemplatePdfRenderView.as_view(), name='admin_template_pdf_render'),
    path('admin/object_dids/',
         views_admin.ObjectDidsView.as_view(), name='admin_object_dids'),

    path('did-registry/<str:did_id>/did.json', ServeDidRegistryView, name="serve_registry_did"),
    path('.well-known/<str:did_id>/did.json', ServeDidView, name="serve_did"),
    path('available/<str:did_id>/', AvailableDidView.as_view(), name="available_did"),
    path('schema/<str:file_name>', SchemaView, name="schema"),
    path('context/base.jsonld', ContextView, name="context"),
    path('context/<str:file_name>', ContextFileView, name="context_file")

    # path('verification_portal/verify/', views_verification_portal.verify,
    #      name="verification_portal_verify")
]

idhub/user/forms.py
import logging

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from idhub.models import DID, VerificableCredential
from oidc4vp.models import Organization
from idhub_auth.models import User
from utils.sanitize_did import sanitize_didweb


logger = logging.getLogger(__name__)


class ProfileForm(forms.ModelForm):
    MANDATORY_FIELDS = ['first_name', 'last_name', 'email']

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class TermsConditionsForm(forms.Form):
    accept_privacy = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        required=False
    )
    accept_legal = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        required=False
    )
    accept_cookies = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        required=False
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def get_label(self, url, read):
        label = _('I read and accepted the')
        label += f' <a class="btn btn-green-user" target="_blank" href="{url}" '
        label += f'title="{read}">{read}</a>'
        return label

    def privacy_label(self):
        url = settings.POLICY_PRIVACY
        read = _("Privacy policy")
        return self.get_label(url, read)

    def legal_label(self):
        url = settings.POLICY_LEGAL
        read = _("Legal policy")
        return self.get_label(url, read)

    def cookies_label(self):
        url = settings.POLICY_COOKIES
        read = _("Cookies policy")
        return self.get_label(url, read)

    def clean(self):
        data = self.cleaned_data
        privacy = data.get("accept_privacy")
        legal = data.get("accept_legal")
        cookies = data.get("accept_cookies")
        if privacy and legal and cookies:
            self.user.accept_gdpr = True
        else:
            self.user.accept_gdpr = False
        return data

    def save(self, commit=True):

        if commit:
            self.user.save()
            return self.user

        return


class RequestCredentialForm(forms.Form):
    did = forms.ChoiceField(label=_("Did"), choices=[])
    credential = forms.ChoiceField(label=_("Credential"), choices=[])

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.lang = kwargs.pop('lang', None)
        self._domain = kwargs.pop('domain', None)
        self.if_credentials = kwargs.pop('if_credentials', None)
        super().__init__(*args, **kwargs)
        self.fields['did'].choices = [
            (x.did, x.label) for x in DID.objects.filter(user=self.user, available=True)
        ]
        self.fields['credential'].choices = [
            (x.id, x.get_type(lang=self.lang)) for x in VerificableCredential.objects.filter(
                user=self.user,
                status=VerificableCredential.Status.ENABLED
            )
        ]

    def save(self, commit=True):
        did = DID.objects.filter(
            user=self.user,
            did=self.data['did']
        ).first()
        cred = VerificableCredential.objects.filter(
            user=self.user,
            id=self.data['credential'],
            status=VerificableCredential.Status.ENABLED
        ).first()

        if not all([cred, did]):
            return

        if commit and self._domain:
            cred.issue(did, domain=self._domain)

            # TODO checkbox "publish inmediately to DLT"
            #if did.type == DID.Types.WEBETH:
            #    cred.call_oracle()

            cred.save()
            return cred

        return


class DemandAuthorizationForm(forms.Form):
    organization = forms.ChoiceField(label=_("Organization"), choices=[])

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.if_credentials = kwargs.pop('if_credentials', None)
        super().__init__(*args, **kwargs)
        self.fields['organization'].choices = [
            (x.id, x.name) for x in Organization.objects.exclude(
                domain=settings.DOMAIN
            )
        ]

    def save(self, commit=True):
        self.org = Organization.objects.filter(
            id=self.data['organization']
        )
        if not self.org.exists():
            return

        self.org = self.org[0]

        if commit:
            url = self.org.demand_authorization()
            if url.status_code == 200:
                return url.json().get('redirect_uri')

        return


class DIDForm(forms.ModelForm):
    class Meta:
        model = DID
        fields = ['label', 'type', 'did']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def clean(self):
        data = self.cleaned_data
        label = data.get("label")
        typ = DID.Types(int(data.get("type")))
        self._did = data.get("did").lower()

        if typ in [DID.Types.WEB, DID.Types.WEBETH]:
            self._did = sanitize_didweb(self._did)

        if DID.objects.filter(did=self._did).first():
            raise ValidationError(_("This DID exist already"))

        if DID.objects.filter(label=label, user=self.user).first():
            raise ValidationError(_("This Label exist already"))

        if not self.instance.is_web:
            self.instance = DID(
                user=self.user,
                type=typ,
                label=label
            )
            return data

        self.instance.label = label
        if self.instance.did != self._did:
            self.instance.did = self._did
            self.instance.get_did_document()
            if settings.DOMAIN != self._did.split(":")[2]:
                self.instance.available = False

        return data

    def save(self, commit=True):

        self.instance.did = self._did
        self.instance.set_did()

        if commit:
            self.instance.save()
            return self.instance

        return

idhub/templates/idhub/user/credential.html
{% extends "idhub/base.html" %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col">
    <h3>
      <i class="{{ icon }}"></i>
      {{ subtitle }}
    </h3>
  </div>
  {% if object.status == 2 and admin_validated %}
    <div class="col text-end">
      <a class="btn btn-green-user me-2" href="{{ url_pdf }}">{% trans 'Download as PDF' %}</a>
    </div>
    <div class="col text-end">
      <a class="btn btn-green-user me-2" href="{{ url_html }}" target="_blank">{% trans 'View as HTML' %}</a>
    </div>
    {% if object.is_webeth %}
    <div class="col text-end">
      <a class="btn btn-green-user me-2" href="{% url 'idhub:call_oracle' object.id %}">{% trans 'Publish to DLT' %}</a>
    </div>
    {% endif %}
  {% endif %}

  <div class="col text-end">
    {% if object.status == 2 and admin_validated %}
      <a class="btn btn-green-user" href="{% url 'idhub:user_credential_json' object.id %}">{% trans 'Download as JSON' %}</a>
    {% endif %}
    {% if object.status == 1 %}
      <a class="btn btn-green-user" href="{% url 'idhub:user_credentials_request' %}">{% trans 'Request credential' %}</a>
    {% endif %}
  </div>
</div>
<div class="row mt-5">
  <div class="col-3">
    <h5>{% trans 'Credential Subject Properties' %}</h5>
  </div>
</div>
<div class="row mt-5">
  <div class="col">
    {% for k, v in object.get_datas %}
    <div class="row mt-3">
      <div class="col-3 text-end">
      <strong>{{ k|capfirst }}:</strong>
      </div>
      <div class="col bg-light text-secondary">
        {{ v }}
      </div>
    </div>
    {% endfor %}
    <div class="row mt-3">
      <div class="col-3 text-end">
      <strong>{% trans 'Issuance date' %}:</strong>
      </div>
      <div class="col bg-light text-secondary">
        {{ object.issued_on|default_if_none:"" }}
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-3 text-end">
      <strong>{% trans 'Status' %}:</strong>
      </div>
      <div class="col bg-light text-secondary">
        {{ object.get_status }}
      </div>
    </div>
  </div>
</div>
{% if object.is_webeth %}
<div class="row mt-5">
  <div class="col-3">
    <h5>{% trans 'Secrets' %}</h5>
  </div>
</div>
<div class="row mt-5">
  <div class="col">
    <div class="row mt-3">
      <div class="col-3 text-end">
      <strong>API_DLT_URL:</strong>
      </div>
      <div class="col bg-light text-secondary">
        {{ API_DLT_URL }}
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-3 text-end">
      <strong>API_DLT_TOKEN:</strong>
      </div>
      <div class="col bg-light text-secondary">
        {{ API_DLT_TOKEN }}
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

idhub/templates/idhub/user/credentials.html
{% extends "idhub/base.html" %}
{% load i18n %}
{% load render_table from django_tables2 %}

{% block content %}
<h3>
  <i class="{{ icon }}"></i>
  {{ subtitle }}
</h3>
{% render_table table %}
{% endblock %}

idhub/templates/idhub/user/credentials_presentation.html
{% extends "idhub/base.html" %}
{% load i18n %}

{% block content %}
<h3>
  <i class="{{ icon }}"></i>
  {{ subtitle }}
</h3>
{% load django_bootstrap5 %}
<form role="form" method="post">
{% csrf_token %}
{% if form.errors %}
<div class="alert alert-danger alert-icon alert-icon-border alert-dismissible" role="alert">
  <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
  <div class="message">
    {% for field, error in form.errors.items %}
      {{ error }}<br />
    {% endfor %}
    <button class="btn-close" type="button" data-dismiss="alert" aria-label="Close"></button>
  </div>
</div>
{% endif %}
{% if form.if_credentials %}
<div class="row">
  <div class="col-sm-4">
    {% bootstrap_form form %}
  </div>
</div>
<div class="form-actions-no-box">
  <a class="btn btn-grey" href="{% url 'idhub:user_credentials' %}">{% trans "Cancel" %}</a>
  <input class="btn btn-green-user" type="submit" name="submit" value="{% trans 'Send' %}" />
</div>
{% else %}
<div class="row">
  <div class="col-sm-4">
    {% trans 'Sorry no there are credentials to present' %}
  </div>
</div>
{% endif %}

</form>
{% endblock %}

idhub/templates/idhub/user/credentials_request.html
{% extends "idhub/base.html" %}
{% load i18n %}

{% block content %}
<h3>
  <i class="{{ icon }}"></i>
  {{ subtitle }}
</h3>
{% load django_bootstrap5 %}
<form role="form" method="post">
{% csrf_token %}
{% if form.errors %}
<div class="alert alert-danger alert-icon alert-icon-border alert-dismissible" role="alert">
  <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
  <div class="message">
    {% for field, error in form.errors.items %}
      {{ error }}<br />
    {% endfor %}
    <button class="btn-close" type="button" data-dismiss="alert" aria-label="Close"></button>
  </div>
</div>
{% endif %}
{% if form.if_credentials %}
<div class="row">
  <div class="col-sm-4">
    {% bootstrap_form form %}
  </div>
</div>
<div class="form-actions-no-box">
  <a class="btn btn-grey" href="{% url 'idhub:user_credentials' %}">{% trans "Cancel" %}</a>
  <input class="btn btn-green-user" type="submit" name="submit" value="{% trans 'Request' %}" />
</div>
{% else %}
<div class="row">
  <div class="col-sm-4">
    {% trans 'Sorry, there are no pending credentials enabled' %}
  </div>
</div>
{% endif %}
</form>
{% endblock %}

idhub/templates/idhub/user/dashboard.html
{% extends "idhub/base.html" %}
{% load i18n %}
{% load render_table from django_tables2 %}

{% block content %}
<h3>
  <i class="{{ icon }}"></i>
  {{ subtitle }}
</h3>
{% if credential_available %}
<div class="container pb-4">
  {% trans 'You have a new credential available, click for go to issue' %}:<br />
   <ul class="list-group list-group-flush">
     {% for c in credential_available %}
     <a href="{% url 'idhub:user_credentials_request' %}" class="list-group-item list-group-item-action py-2 border btn-green-admin mb-3">
         <div class="d-flex justify-content-between align-items-center">
           <div>
             <strong class="h6">{{ c.type }}</strong>
             {% if c.code %}<span class="text-muted ms-2">({{ c.code }})</span>{% endif %}
             {% if c.description %}<div class="text-muted small">{{ c.description }}</div>{% endif %}
           </div>
           <div class="d-flex align-items-center">
              <span class="badge rounded-pill bg-success">
               {% trans "issue" %}
             </span>

             <div class="text-end ms-3">
                 <i class="far fa-calendar-alt text-muted me-1 small"></i>
                 <span class="text-muted small">{% trans "Enabled" %}</span>
               <div class="small text-muted">{{ c.created_on|date:"Y-m-d" }}</div>
             </div>
           </div>
         </div>
       </a>
     {% endfor %}
   </ul>
</div>
{% endif %}

{% render_table table %}

{% endblock %}

idhub/templates/idhub/user/dids.html
{% extends "idhub/base.html" %}
{% load i18n %}
{% load render_table from django_tables2 %}

{% block content %}
<h3>
  <i class="{{ icon }}"></i>
  {{ subtitle }}
</h3>
{% render_table table %}
<div class="form-actions-no-box">
    <a class="btn btn-green-user" href="{% url 'idhub:user_dids_new' %}">{% translate "Add Identity" %} <i class="bi bi-plus"></i></a>
</div>
<!-- Modal -->
{% for d in dids.all %}
<div class="modal" id="confirm-delete-{{ d.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{% trans 'Delete DID' %} "{{ d.label }}"</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {% trans 'Are you sure that you want delete this DID?' %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans 'Cancel' %}</button>
        <a href="{% url 'idhub:user_dids_del' d.id %}" type="button" class="btn btn-danger">{% trans 'Delete' %}</a>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}

idhub/templates/idhub/user/gdpr.html
{% extends "idhub/base.html" %}
{% load i18n %}

{% block content %}
<h3>
  <i class="{{ icon }}"></i>
  {{ subtitle }}
</h3>
Gdpr info<br/>
If you want accept or revoke the Gdpr go to: 
    <a class="btn btn-green-user" href="{% url 'idhub:user_terms_and_conditions' %}">Terms and conditions</a>
{% endblock %}

idhub/templates/idhub/user/terms_conditions.html
{% extends "idhub/base.html" %}
{% load i18n %}

{% block content %}
<h3>
  <i class="{{ icon }}"></i>
  {{ subtitle }}
</h3>
{% load django_bootstrap5 %}
<form role="form" method="post">
{% csrf_token %}
{% if form.errors %}
<div class="alert alert-danger alert-icon alert-icon-border alert-dismissible" role="alert">
  <div class="icon"><span class="mdi mdi-close-circle-o"></span></div>
  <div class="message">
    {% for field, error in form.errors.items %}
      {{ error }}<br />
    {% endfor %}
    <button class="btn-close" type="button" data-dismiss="alert" aria-label="Close"></button>
  </div>
</div>
{% endif %}
<div class="row mt-4">
  <div class="col">
    {{ form.accept_privacy }}
    {{ form.privacy_label|safe }}
  </div>
</div>
<div class="row mt-2">
  <div class="col">
    {{ form.accept_legal }}
    {{ form.legal_label|safe }}
  </div>
</div>
<div class="row mt-2">
  <div class="col">
    {{ form.accept_cookies }}
    {{ form.cookies_label|safe }}
  </div>
</div>
<div class="form-actions-no-box mt-4">
    <a href="javascript:accepts();" type="button" class="btn btn-green-user">{% trans 'Confirm' %}</a>
</div>

<!-- Modal -->
<div class="modal" id="gdpr" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{% trans 'Data protection' %}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      {% blocktrans %}
        <p>If you do not accept all the terms and conditions of this service you will not be able
to continue.
        <br /><br />
        Are you sure to opt out of using this service?</p>
      {% endblocktrans %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans 'No' %}</button>
        <input id="submit" class="btn btn-green-user" type="submit" name="submit" value="{% translate 'Yes' %}" />
      </div>
    </div>
  </div>
</div>
</form>
{% endblock %}

{% block extrascript %}
<script>
$(document).ready(function() {
});

function accepts() {
  var privacy = $("#id_accept_privacy").prop("checked");
  var policy = $("#id_accept_legal").prop("checked");
  var cookies = $("#id_accept_cookies").prop("checked");
  if (privacy && policy && cookies) {
    $("#submit").trigger("click");
  } else {
    $("#gdpr").modal("show");
  }
}
</script>
{% endblock %}